const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {atomicJSON}=require('../store.cjs');
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
function readText(file,limit=8e6){if(fs.statSync(file).size>limit)throw Error('文件过大，未读取');return new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(fs.readFileSync(file));}
function atomicText(file,text){const bytes=Buffer.isBuffer(text)?text:Buffer.from(text,'utf8'),temp=file+'.rmodifier-'+crypto.randomUUID();fs.mkdirSync(path.dirname(file),{recursive:true});try{fs.writeFileSync(temp,bytes,{flag:'wx'});const fd=fs.openSync(temp,'r+');try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}if(hash(fs.readFileSync(temp))!==hash(bytes))throw Error('写入核对失败');fs.renameSync(temp,file);}finally{if(fs.existsSync(temp))fs.unlinkSync(temp);}}
function physical(file){let dir=path.resolve(file);const parts=[];while(!fs.existsSync(dir)){const parent=path.dirname(dir);if(parent===dir)break;parts.unshift(path.basename(dir));dir=parent;}return path.resolve(fs.realpathSync.native(dir),...parts);}
function inside(root,file){const rel=path.relative(physical(root),physical(file));return rel!==''&&!rel.startsWith('..'+path.sep)&&!path.isAbsolute(rel)&&rel!=='..';}
function checkedWrite(file,content,expected,backupRoot){const before=fs.existsSync(file)?fs.readFileSync(file):null;if((before?hash(before):null)!==expected)throw Error('文件已被其他程序修改。请另存一份，或重新打开磁盘文件后核对，当前内容仍保留。');let backup=null;if(before){backup=path.join(backupRoot,Date.now()+'-'+crypto.randomUUID(),path.basename(file));fs.mkdirSync(path.dirname(backup),{recursive:true});fs.writeFileSync(backup,before,{flag:'wx'});if(hash(fs.readFileSync(backup))!==expected)throw Error('备份核对失败');}if((fs.existsSync(file)?hash(fs.readFileSync(file)):null)!==expected)throw Error('文件在备份时发生变化，已停止覆盖');atomicText(file,content);return {hash:hash(Buffer.from(content)),backup};}
module.exports={readText,atomicText,atomicJSON,hash,inside,checkedWrite};
