'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {_electron:electron}=require('C:/Users/hello/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const project=path.resolve(__dirname,'..'),game=path.resolve(project,'../..'),root=path.join(project,'build/out/barks-ui-'+Date.now()),checks=[],errors=[];
fs.mkdirSync(path.join(root,'game'),{recursive:true});fs.copyFileSync(path.join(game,'text_zh.xml'),path.join(root,'game/text_zh.xml'));
const C=require('../desktop/barks/core.js');
async function main(){const application=await electron.launch({executablePath:path.join(project,'node_modules/electron/dist/electron.exe'),args:[path.join(__dirname,'barks-harness.cjs')],env:{...process.env,BARKS_TEST_ROOT:root},timeout:30000});const page=await application.firstWindow();page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('Electron Security Warning'))errors.push(m.text());});const ui=page.frameLocator('#barks-frame');
 const waitState=async value=>page.waitForFunction(v=>window.states.barks?.dirty===v,value);
 const capture=async name=>{const encoded=await application.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].webContents.capturePage()).toPNG().toString('base64'));fs.writeFileSync(path.join(root,name),Buffer.from(encoded,'base64'));};
 const saveDialog=async(file,canceled=false)=>application.evaluate(({dialog},data)=>{dialog.showSaveDialog=async()=>data.canceled?{canceled:true}:{canceled:false,filePath:data.file};},{file,canceled});
 const openDialog=async file=>application.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);
 try{
  await ui.locator('[data-edit]').first().waitFor();assert.match(await ui.locator('#scene-title').innerText(),/破解/);assert.match(await ui.locator('#total-count').innerText(),/17.*102.*976/);checks.push('Chinese corpus opened through host IPC');
  await capture('01-barks.png');
  const area=()=>ui.locator('[data-edit]').first();await area().fill('整合台词：密码又是123！');await waitState(true);assert.equal((await page.evaluate(()=>window.states.loot)).revision,8);checks.push('Editing sets only bark dirty state');
  await ui.getByText('给自己留个备注',{exact:true}).click();await ui.locator('#line-note').fill('给作者的备注，不进入游戏');await ui.locator('#line-note').blur();
  await page.locator('#showOther').click();await page.locator('#showBarks').click();assert.equal(await area().inputValue(),'整合台词：密码又是123！');assert.equal(await ui.locator('#line-note').inputValue(),'给作者的备注，不进入游戏');checks.push('Workspace switch preserves text, note and history');
  await ui.locator('#undo').click();assert.equal(await ui.locator('#line-note').inputValue(),'');await ui.locator('#redo').click();assert.equal(await ui.locator('#line-note').inputValue(),'给作者的备注，不进入游戏');checks.push('Undo and redo include notes');
  await ui.locator('[data-disable]').first().check();assert.match(await ui.locator('#speech-bubble').innerText(),/安静/);await ui.locator('[data-disable]').first().uncheck();await ui.locator('[data-mark]').first().check();await ui.locator('#preview-filter').check();assert.match(await ui.locator('#preview-reason').innerText(),/过滤|粗口/);await ui.locator('#preview-filter').uncheck();checks.push('Disabled lines and profanity filtering preview');
  const draft=path.join(root,'中文 台词.barks.json');await saveDialog(draft,true);await ui.locator('#save-project').click();await page.waitForTimeout(180);await waitState(true);assert.equal(fs.existsSync(draft),false);checks.push('Canceled native dialog leaves dirty state');
  await saveDialog(draft);await ui.locator('#save-project').click();await waitState(false);const saved=await C.readProject(JSON.parse(fs.readFileSync(draft,'utf8')));assert.equal(saved.entries['pip/hack'][0].text,'整合台词：密码又是123！');assert.equal(saved.entries['pip/hack'][0].note,'给作者的备注，不进入游戏');checks.push('Native save writes valid v1 draft to disk');
  const exported=path.join(root,'导出语言.xml');await saveDialog(exported);await ui.locator('#export-button').click();await ui.getByRole('button',{name:'另存游戏文本',exact:true}).click();await ui.locator('#modal').waitFor({state:'hidden'});assert.ok(fs.readFileSync(exported,'utf8').includes('整合台词'));assert.ok(!fs.readFileSync(exported,'utf8').includes('给作者的备注'));checks.push('Native XML export writes full file without author notes');
  // Save captures revision before await; edit during the delayed native dialog.
  await application.evaluate(({dialog})=>{dialog.showSaveDialog=()=>new Promise(resolve=>globalThis.barksTest.releaseDialog=resolve);});await area().fill('保存请求捕获的版本');await ui.locator('#save-project').click();await page.waitForTimeout(150);await area().fill('等待期间继续写的新版本');await application.evaluate((_electron,file)=>globalThis.barksTest.releaseDialog({canceled:false,filePath:file}),draft);await page.waitForTimeout(250);await waitState(true);assert.equal(JSON.parse(fs.readFileSync(draft,'utf8')).entries['pip/hack'][0].text,'保存请求捕获的版本');assert.equal(await area().inputValue(),'等待期间继续写的新版本');checks.push('Late save response never marks a newer edit saved');
  await saveDialog(draft);await area().press('Control+s');await waitState(false);assert.equal(JSON.parse(fs.readFileSync(draft,'utf8')).entries['pip/hack'][0].text,'等待期间继续写的新版本');checks.push('Ctrl+S works inside a text field');
  const beforeCalls=await page.evaluate(()=>window.states.barks.savedRevision);await area().evaluate(el=>el.dispatchEvent(new KeyboardEvent('keydown',{key:'s',ctrlKey:true,isComposing:true,bubbles:true,cancelable:true})));await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.states.barks.savedRevision),beforeCalls);checks.push('Composition key event is not used as a shortcut');
  await openDialog(draft);await ui.locator('#open-button').click();await ui.locator('#toast').filter({hasText:/已经打开/}).waitFor();assert.equal(await area().inputValue(),'等待期间继续写的新版本');checks.push('Native open reloads existing v1 draft');
  await area().fill('重启恢复测试');await page.evaluate(()=>window.editors.barks.recover());await page.reload();await ui.locator('[data-edit]').first().waitFor();assert.equal(await area().inputValue(),'重启恢复测试');await waitState(true);checks.push('Reload restores durable unsaved draft');
  await application.evaluate(({dialog})=>{dialog.showMessageBox=async()=>({response:1});});await ui.locator('#export-button').click();await ui.getByRole('button',{name:'备份并写入游戏',exact:true}).click();await ui.locator('#modal').waitFor({state:'hidden'});assert.match(fs.readFileSync(path.join(root,'game/text_zh.xml'),'utf8'),/重启恢复测试/);checks.push('UI applies to isolated game with backup');
  await area().fill('第二次写入');await ui.locator('#export-button').click();await ui.getByRole('button',{name:'备份并写入游戏',exact:true}).click();await ui.locator('#modal').waitFor({state:'hidden'});assert.match(fs.readFileSync(path.join(root,'game/text_zh.xml'),'utf8'),/第二次写入/);await ui.locator('#export-button').click();await ui.getByRole('button',{name:'恢复上次写入',exact:true}).click();await ui.locator('#modal').waitFor({state:'hidden'});assert.match(fs.readFileSync(path.join(root,'game/text_zh.xml'),'utf8'),/重启恢复测试/);checks.push('UI consecutive application and last-write restoration');
  await application.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(900,800));await page.waitForTimeout(150);assert.ok(await ui.locator('#save-project').isVisible());await capture('02-barks-narrow.png');checks.push('900px window retains top actions');
  await application.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setSize(1440,1020);w.webContents.setZoomFactor(1.5);});await page.waitForTimeout(150);await capture('03-barks-150.png');checks.push('150 percent zoom renders usable layout');
  assert.deepEqual(errors,[]);checks.push('No JavaScript or CSP errors');
 }catch(e){await capture('failure.png').catch(()=>{});console.error(await ui.locator('body').innerText().catch(()=>''));throw e;}finally{fs.writeFileSync(path.join(root,'results.json'),JSON.stringify({at:new Date().toISOString(),passed:checks.length,checks,errors,gameWrites:'isolated fake game only',root},null,2));await application.evaluate(()=>process.exit(0)).catch(()=>{});await application.close().catch(()=>{});}
 console.log(JSON.stringify({passed:checks.length,errors,root},null,2));}
main().catch(e=>{console.error(e);process.exitCode=1;});
