const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {NativeDocument,hash}=require('../../desktop/map/native-document.cjs'),M=require('../../desktop/map/document.js');
const game=path.resolve(__dirname,'../../../..');
function fixture(){return '\ufeff<?xml version="1.0"?>\r\n<all version="x"><!--root--><land/><extension v="keep"/>'+M.blankRoom('甲').replace('<options/>','<obj id="box" x="2" y="4" custom="unchanged"><scr><![CDATA[x < 3]]></scr></obj><obj id="unknown"/><options mystery="yes"/><rrPlan opaque="1"/>')+M.blankRoom('乙')+'</all>\r\n';}
test('31 full map sources retain exact bytes and unique identities',()=>{let files=0,rooms=0;for(const f of fs.readdirSync(path.join(game,'Rooms')).filter(f=>f.endsWith('.xml'))){const raw=fs.readFileSync(path.join(game,'Rooms',f),'utf8');let d;try{d=M.parse(raw);}catch{continue;}const n=new NativeDocument(raw);assert.equal(n.raw,raw);assert.equal(n.state.dirty,false);assert.equal(n.projection().rooms.length,d.rooms.length);assert.equal(hash(n.raw),hash(raw));files++;rooms+=d.rooms.length;}assert.equal(files,31);assert.equal(rooms,662);});
test('one object edit, including missing code, preserves every other byte',()=>{const raw=fixture(),d=new NativeDocument(raw),o=d.projection().rooms[0].nodes.find(n=>n.kind==='obj');const changed=o.raw.replace('x="2"','x="3"');d.apply([{kind:'replaceInput',nodeKey:o.key,raw:changed}]);assert.equal(d.raw,raw.replace(o.raw,changed));assert.ok(!d.raw.includes('code='));assert.ok(d.undo());assert.equal(d.raw,raw);assert.ok(d.redo());assert.equal(d.raw,raw.replace(o.raw,changed));});
test('invalid pending input survives snapshot/recovery and remains dirty',()=>{const d=new NativeDocument(fixture()),o=d.projection().rooms[0].nodes.find(n=>n.kind==='obj'),raw='<obj x="';d.capture([{fieldKey:'SelObj',nodeKey:o.key,raw,error:'unfinished'}],{selectedKey:o.key});const s=d.snapshot(),copy=new NativeDocument(s.raw,{identity:s.identity});copy.restore(s);assert.equal(copy.inputs[0].raw,raw);assert.equal(copy.state.canSave,false);assert.equal(copy.state.dirty,true);assert.throws(()=>copy.undo(),/属性/);});
test('room copy/remove keep opaque data and stable object identity',()=>{const d=new NativeDocument(fixture()),first=d.projection().rooms[0];d.apply([{kind:'createRoom',copyOf:first.key,name:'复制'}]);const copied=d.projection().rooms[2];assert.ok(copied.raw.includes('<rrPlan opaque="1"/>'));assert.notEqual(copied.nodes[0].key,first.nodes[0].key);d.apply([{kind:'removeNode',nodeKey:copied.key}]);assert.equal(d.raw.replace(/\s/g,''),fixture().replace(/\s/g,''));assert.equal(d.projection().rooms[0].nodes[0].key,first.nodes[0].key);});
test('terrain changes only one token and affected connector slot',()=>{const raw=fixture(),d=new NativeDocument(raw),r=d.projection().rooms[0],row=M.parse(raw).rooms[0].children.filter(n=>n.name==='a')[10];d.apply([{kind:'paint',roomKey:r.key,cells:[{x:10,y:10,layers:{1:'A'}}]}]);assert.equal(d.raw,M.patch(raw,[{start:row.openEnd+20,end:row.openEnd+21,value:'A'}]));const before=M.parse(d.raw).rooms[0].children.find(n=>n.name==='doors');const old=M.text(before).split('.');d.apply([{kind:'paint',roomKey:r.key,cells:[{x:47,y:3,layers:{1:'A'}}]}]);const after=M.text(M.parse(d.raw).rooms[0].children.find(n=>n.name==='doors')).split('.');assert.equal(after[0],'0');assert.deepEqual(after.slice(1),old.slice(1));});
test('complex row rejects edits atomically, remains untouched on no-op',()=>{let raw=fixture();raw=raw.replace('<a>','<a><!--preserve-->');const d=new NativeDocument(raw);assert.throws(()=>d.apply([{kind:'paint',roomKey:d.keys[0].key,cells:[{x:1,y:0,layers:{1:'A'}}]}]),/CDATA/);assert.equal(d.raw,raw);assert.equal(d.state.dirty,false);});
test('stale revision and duplicate room identity are rejected',()=>{const d=new NativeDocument(fixture());assert.throws(()=>d.apply([],{expectedRevision:50}),/过期/);assert.throws(()=>d.apply([{kind:'createRoom',name:'甲'}]),/已存在/);assert.equal(d.raw,fixture());});
test('entity-encoded cell delimiters cannot collapse a row',()=>{const raw='<all><room name="r"><a>'+Array(48).fill('_').join('&#46;')+'</a></room></all>',d=new NativeDocument(raw);assert.throws(()=>d.apply([{kind:'paint',roomKey:d.keys[0].key,cells:[{x:0,y:0,layers:{1:'A'}}]}]),/编码分隔符/);assert.equal(d.raw,raw);});
test('Flash display newline conversion cannot rewrite untouched script bytes',()=>{const original='<obj id="safe" x="1"><scr><![CDATA[one\r\ntwo\nthree\rfour]]></scr></obj>',raw='<all><room name="r">'+original+'</room></all>',d=new NativeDocument(raw),o=d.projection().rooms[0].nodes[0],display=original.replace(/\r\n?/g,'\n').replace(/\n/g,'\r');d.apply([{kind:'replaceInput',nodeKey:o.key,displayBase:display,raw:display.replace('x="1"','x="2"')}]);assert.equal(d.raw,raw.replace('x="1"','x="2"'));});
test('one full-canvas rectangle changes 1200 cells in one undoable transaction',()=>{const raw=fixture(),d=new NativeDocument(raw),roomKey=d.keys[0].key,ops=Array.from({length:1200},(_,i)=>({kind:'paint',roomKey,cells:[{x:i%48,y:Math.floor(i/48),layers:{1:'A'}}]}));d.apply(ops);assert.ok(M.cells(M.parse(d.raw).rooms[0]).flat().every(c=>c==='A'));assert.equal(d.undoStack.length,1);d.undo();assert.equal(d.raw,raw);});
