// Drives the real candidate Flash controls; all writes stay in one fake game installation.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {NativeMapModule}=require('../../desktop/map/native-ui-module.cjs'),{hash}=require('../../desktop/map/native-document.cjs'),M=require('../../desktop/map/document.js');
const project=path.resolve(__dirname,'../..'),installed=path.resolve(project,'../..');
const root=path.join(project,'build/out/map-native-ui',crypto.randomUUID()),gameRoot=path.join(root,'隔离游戏 with spaces'),dataRoot=path.join(gameRoot,'mods/RModifier'),componentRoot=path.join(project,'map-editor/native-ui/component');
const checks=[];let mod,receipt,saveWait,openWait,savedPath=path.join(root,'工作副本.xml');
const ok=n=>{checks.push(n);console.log('PASS '+n);};
const dialog={showSaveDialog:async()=>saveWait?new Promise(r=>{saveWait.resolve=r;}):({canceled:false,filePath:savedPath}),showOpenDialog:async()=>openWait?new Promise(r=>{openWait.resolve=r;}):({canceled:false,filePaths:[savedPath]})};
const surface={attach:async b=>{assert.ok(b.pid);return {dpi:192};},setVisible:async()=>{},focus:async()=>{},detach:async()=>{}};
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 fs.mkdirSync(path.join(gameRoot,'Rooms'),{recursive:true});fs.mkdirSync(dataRoot,{recursive:true});fs.mkdirSync(path.join(gameRoot,'runtimes/air'),{recursive:true});
 // Read-only dependencies via links; every prospective writable path is checked by MapWorkspace.
 for(const f of ['adl64.exe','texture.swf','texture1.swf','sprite.swf','sprite1.swf','text_zh.xml','text_en.xml','text_ru.xml'])fs.linkSync(path.join(installed,f),path.join(gameRoot,f));
 fs.symlinkSync(path.join(installed,'runtimes/air/win64'),path.join(gameRoot,'runtimes/air/win64'),'junction');
 for(const f of fs.readdirSync(path.join(installed,'Rooms')).filter(f=>f.endsWith('.xml')))fs.copyFileSync(path.join(installed,'Rooms',f),path.join(gameRoot,'Rooms',f));
 const source=path.join(gameRoot,'Rooms/rooms_plant.xml'),raw=fs.readFileSync(source,'utf8'),sourceHash=hash(raw);
 mod=new NativeMapModule({dialog,getWindow:()=>null,onError:e=>console.error('ACTION ERROR',e)});
 await mod.mount({gameRoot,dataRoot,componentRoot,sessionRoot:path.join(root,'sessions'),testRoot:root,epoch:crypto.randomUUID(),surface});
 assert.equal(mod.doc.raw,raw);assert.equal((await mod.flush('inspect')).state.dirty,false);ok('actual original Flash UI loads full map without normalization');
 const uiCapture=await mod.session.request('capture');assert.ok(fs.statSync(path.join(mod.session.root,uiCapture.png)).size>1000);
 const viewport=await mod.setViewport({zoom:1.25,panX:-500,panY:-300,fit:false});assert.equal(viewport.fit,true);assert.equal(viewport.panX,0);assert.equal(viewport.panY,0);assert.equal(viewport.deviceScale,2);assert.equal(viewport.effectiveScale,Math.min(viewport.width/1800,viewport.height/950));const measured=await mod.setViewport({deviceScale:2,clientWidth:viewport.width*2});assert.equal(measured.uiScale,1);assert.equal(measured.effectiveScale,viewport.effectiveScale);ok('original stage always fits the full viewport, including legacy pan/zoom recovery and 200% DPI');
 const room=mod.doc.projection().rooms.find(r=>r.nodes.some(n=>n.kind==='obj'));
 const obj=room.nodes.find(n=>n.kind==='obj');
 await mod.session.request('test',{action:{kind:'select',room:room.name,key:obj.key}});
 const changed=M.attribute(obj.raw,M.parse?require('../../desktop/map/xml.js').scanXml(obj.raw):null,'customNote','原界面测试');
 await mod.session.request('test',{action:{kind:'input',raw:changed}});
 await mod.session.request('test',{action:{kind:'check'}});
 await mod.flush('inspect');assert.equal(mod.doc.raw,raw.replace(obj.raw,changed));assert.equal(mod.state.dirty,true);ok('real object attribute field commits only selected original XML');
 const save=await mod.saveDraft();assert.equal(save.status,'saved',JSON.stringify(save));assert.equal(fs.readFileSync(savedPath,'utf8'),mod.doc.raw);assert.ok(save.receipt);ok('save work copy with revision/content receipt');
 const edited=mod.doc.raw;await mod.action('open');assert.equal(mod.doc.raw,edited);assert.equal((await mod.flush('inspect')).state.dirty,false);ok('reopen saved work copy in original Flash UI');
 const second=mod.doc.projection().rooms.find(r=>r.name===room.name),obj2=second.nodes.find(n=>n.kind==='obj');
 await mod.session.request('test',{action:{kind:'select',room:second.name,key:obj2.key}});
 await mod.session.request('test',{action:{kind:'input',raw:'<obj x="'}});
 const invalid=await mod.flush('close');assert.equal(invalid.status,'invalid');assert.equal(invalid.state.dirty,true);assert.equal(mod.doc.raw,edited);assert.equal((await mod.saveDraft()).status,'invalid');
 const recovery=await mod.recover();assert.equal(recovery.status,'recovered');receipt=recovery.receipt;assert.equal(JSON.parse(fs.readFileSync(mod.recoveryFile,'utf8')).inputs[0].raw,'<obj x="');ok('invalid XML blocks save and survives durable recovery with selection');
 await mod.restoreRecovery();const resumed=await mod.flush('inspect');assert.equal(resumed.status,'invalid');assert.equal(mod.doc.inputs[0].raw,'<obj x="');ok('restored original input field retains invalid raw text');
 await mod.session.request('test',{action:{kind:'input',raw:obj2.raw}});await mod.flush('inspect');
 await mod.session.request('test',{action:{kind:'paint',layer:1,id:'A',x:10,y:10,x2:11,y2:11}});await mod.flush('inspect');assert.notEqual(mod.doc.raw,edited);const painted=mod.doc.raw;await mod.action('undo');assert.equal(mod.doc.raw,edited);await mod.action('redo');assert.equal(mod.doc.raw,painted);ok('real rectangular paint and native canvas undo/redo');
 await mod.session.request('test',{action:{kind:'copyRoom',name:'原房间复制测试'}});await mod.flush('inspect');assert.ok(mod.doc.projection().rooms.some(r=>r.name==='原房间复制测试'));ok('original update-list control copies full room');
 const selected=mod.doc.projection().rooms.find(r=>r.name==='原房间复制测试'),current=selected.nodes.find(n=>n.kind==='obj');
 await mod.session.request('test',{action:{kind:'select',room:selected.name,key:current.key}});
 const beforeSave=mod.doc.raw;saveWait={};const waitingSave=mod.saveDraft({as:true});while(!saveWait.resolve)await delay(30);
 let undone=false;const queuedUndo=mod.action('undo').then(()=>{undone=true;});
 await mod.session.request('test',{action:{kind:'input',raw:current.raw.replace('customNote="原界面测试"','customNote="等待保存时再改"')}});await mod.session.request('test',{action:{kind:'check'}});assert.equal(undone,false);
 saveWait.resolve({canceled:false,filePath:savedPath});saveWait=null;const concurrent=await waitingSave;assert.equal(concurrent.status,'saved');assert.equal(concurrent.receipt,null);assert.equal(fs.readFileSync(savedPath,'utf8'),beforeSave);await queuedUndo;assert.equal(mod.doc.raw,beforeSave);ok('save captures its revision while newer edit survives and next action waits');
 openWait={};const waitingOpen=mod.action('open');while(!openWait.resolve)await delay(30);
 const oldDocument=mod.doc.documentId;await mod.session.request('test',{action:{kind:'input',raw:'<obj invalid="'}});
 openWait.resolve({canceled:false,filePaths:[savedPath]});openWait=null;await waitingOpen;assert.notEqual(mod.doc.documentId,oldDocument);
 const backups=fs.readdirSync(path.dirname(mod.recoveryFile)).filter(f=>f.includes('.switch-')).map(f=>JSON.parse(fs.readFileSync(path.join(path.dirname(mod.recoveryFile),f),'utf8')));assert.ok(backups.some(b=>b.documentId===oldDocument&&b.inputs.some(i=>i.raw==='<obj invalid="')));
 const stable=mod.doc.raw;const stale=await mod.event({kind:'commit',documentId:oldDocument,expectedRevision:0,payload:{operations:[]}});assert.equal(stale.stale,true);assert.equal(mod.doc.raw,stable);ok('open dialog late input archived, stale document event rejected');
 await mod.session.request('test',{action:{kind:'fileName',raw:'新副本名字'}});const filenameSave=await mod.saveDraft();assert.equal(filenameSave.status,'saved');assert.equal((await mod.flush('inspect')).state.dirty,false);ok('pending filename is saved through host transaction');
 await mod.session.request('test',{action:{kind:'language',language:'en'}});await delay(250);assert.equal(JSON.parse(fs.readFileSync(path.join(dataRoot,'config/native-maps/preferences.json'),'utf8')).language,'en');assert.equal(mod.state.dirty,false);ok('language preference lives in data root without dirtying map');
 await mod.session.request('test',{action:{kind:'preview'}});
 let preview;const until=Date.now()+45000;do{await delay(200);preview=(await mod.session.request('inspect')).input.view.preview;}while((!preview?.ready||preview.busy)&&Date.now()<until);
 assert.equal(preview?.open,true);assert.equal(preview?.ready,true);assert.equal(preview?.busy,false);await mod.activate(false);await mod.activate(true);assert.deepEqual((await mod.session.request('inspect')).input.view.preview,preview);ok('original PreviewPanel renders and persists across page visibility changes');
 await mod.setViewport({fit:true});const previewCapture=await mod.session.request('capture');
 savedPath=path.join(root,'原面板导出.png');await mod.session.request('test',{action:{kind:'exportPreview'}});const exportUntil=Date.now()+10000;while(!fs.existsSync(savedPath)&&Date.now()<exportUntil)await delay(50);const png=fs.readFileSync(savedPath);assert.equal(png.readUInt32BE(16),1920);assert.equal(png.readUInt32BE(20),1000);ok('original preview export uses host dialog and verified PNG file');
 const locked1=await mod.suspend('dialog'),locked2=await mod.suspend('nested-dialog');assert.ok(locked1.locked&&locked2.locked);await mod.resume();assert.equal(mod.suspensions,1);await mod.resume();assert.equal(mod.suspensions,0);ok('nested host dialogs resume only after last lock');
 assert.equal(hash(fs.readFileSync(source)),sourceHash);assert.equal(hash(fs.readFileSync(path.join(installed,'Rooms/rooms_plant.xml'))),sourceHash);ok('source maps unchanged');
 const end=await mod.recover();receipt=end.receipt;await mod.dispose(receipt);assert.equal(mod.session.exited,0);ok('only owned candidate process closes after matching recovery receipt');
 const previousSession=mod.session.root,docId=mod.doc.documentId;mod=new NativeMapModule({dialog,getWindow:()=>null});await mod.mount({gameRoot,dataRoot,componentRoot,sessionRoot:path.join(root,'sessions'),testRoot:root,epoch:crypto.randomUUID(),surface});assert.equal(mod.doc.documentId,docId);assert.equal(mod.recovered,true);let restored;const restoreUntil=Date.now()+45000;do{await delay(200);restored=(await mod.session.request('inspect')).input.view.preview;}while((!restored?.ready||restored.busy)&&Date.now()<restoreUntil);assert.equal(restored?.open,true);assert.equal(restored?.ready,true);const lastRecovery=await mod.recover();await mod.dispose(lastRecovery.receipt);ok('new process restores canonical document, selection and original preview state');
 fs.writeFileSync(path.join(root,'report.json'),JSON.stringify({passed:true,checks,root,session:previousSession,restartedSession:mod.session.root,preview,captures:[uiCapture.png,previewCapture.png]},null,2));console.log(JSON.stringify({passed:true,checks:checks.length,root}));
})().catch(e=>{fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'failure.json'),JSON.stringify({error:e.stack,checks,session:mod?.session?.root,output:mod?.session?.output},null,2));console.error(e);process.exitCode=1;}).finally(async()=>{if(mod?.session?.exited===undefined){try{const r=await mod.recover();await mod.dispose(r.receipt);}catch{await mod?.session?.stop();}}});
