'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {MapWorkspace}=require('../../desktop/map/workspace.cjs'),{SceneLibrary,additions}=require('../../desktop/map/scene-library.cjs'),{NativeDocument,hash}=require('../../desktop/map/native-document.cjs');
const M=require('../../desktop/map/document.js');
const project=path.resolve(__dirname,'../..'),installed=path.resolve(project,'../..');
function setup(){const root=path.join(project,'build/out/map-library-unit',crypto.randomUUID()),gameRoot=path.join(root,'game'),dataRoot=path.join(gameRoot,'mods/RModifier');fs.mkdirSync(dataRoot,{recursive:true});fs.cpSync(path.join(installed,'Rooms'),path.join(gameRoot,'Rooms'),{recursive:true});const workspace=new MapWorkspace({gameRoot,dataRoot,testRoot:root,componentRoot:path.join(project,'map-editor/native-ui/component')});return {root,workspace,lib:new SceneLibrary(workspace)};}
test('all 31 installed map sources and 662 rooms are reachable without editing their bytes',()=>{const {lib}=setup(),entries=lib.scan();assert.equal(entries.length,31);assert.equal(entries.reduce((n,e)=>n+e.count,0),662);assert(entries.every(e=>!e.error));assert.equal(entries.find(e=>e.sourceFile==='rooms_mane.xml').name,'马哈顿废墟');assert(entries.some(e=>e.fixed));assert(entries.some(e=>e.random));for(const e of entries)assert.equal(lib.open(e.id).raw,fs.readFileSync(path.join(installed,'Rooms',e.sourceFile),'utf8'));});
test('parallel pool saves a byte-identical baseline and only publishes changed variants',()=>{const {lib,workspace}=setup();lib.scan();const original=lib.get('original:rooms_plant.xml'),v=lib.create({sourceId:original.id,name:'我的工厂'});assert.equal(v.raw,original.raw);assert.throws(()=>lib.publish(v.libraryId),/还没有/);const d=new NativeDocument(v.raw),room=d.keys[0].key;d.apply([{kind:'paint',roomKey:room,cells:[{x:5,y:5,layers:{2:'B'}}]}]);lib.save(v.id,d.raw);const result=lib.publish(v.libraryId),s=result.selections['rooms_plant.xml'];assert.equal(s.mode,'mix');assert.equal(s.count,1);const extra=M.parse(fs.readFileSync(path.join(workspace.dataRoot,s.file),'utf8'));assert.equal(extra.rooms.length,1);assert.match(extra.rooms[0].attrs.name,/^rm_/);assert.equal(fs.readFileSync(original.file,'utf8'),original.raw);assert.equal(hash(fs.readFileSync(path.join(workspace.dataRoot,s.file))),s.sha256);assert.equal(lib.publish(original.id).selections['rooms_plant.xml'],undefined);});
test('unchanged rooms do not acquire extra probability; linked back rooms get private identities',()=>{const base='<all><land/>'+M.blankRoom('main').replace('<options/>','<options back="back"/>')+M.blankRoom('back').replace('<options/>','<options tip="back"/>')+'</all>';assert.equal(additions(base,base,crypto.randomUUID()).count,0);const d=new NativeDocument(base);d.apply([{kind:'paint',roomKey:d.keys[0].key,cells:[{x:4,y:4,layers:{1:'C'}}]}]);const a=additions(d.raw,base,crypto.randomUUID()),p=M.parse(a.raw);assert.equal(a.count,1);assert.equal(a.dependencies,1);assert.equal(p.rooms[0].children.find(n=>n.name==='options').attrs.back,p.rooms[1].attrs.name);assert.equal(new Set(p.rooms.map(r=>r.attrs.name)).size,2);});
test('special-only edits remain saved but cannot silently become random rooms',()=>{const base='<all><land/>'+M.blankRoom('entry').replace('<options/>','<options tip="beg0"/>')+'</all>',d=new NativeDocument(base);d.apply([{kind:'paint',roomKey:d.keys[0].key,cells:[{x:3,y:3,layers:{1:'C'}}]}]);const a=additions(d.raw,base,crypto.randomUUID());assert.equal(a.count,0);assert.deepEqual(a.skipped,['entry']);});
test('save refuses external concurrent changes and preserves original, backup and Unicode',()=>{const {lib}=setup();lib.scan();const v=lib.create({sourceId:'original:rooms_sewer.xml',name:'下水道🐎新房间'}),file=lib.get(v.libraryId).file;fs.appendFileSync(file,'\n<!-- external -->');assert.throws(()=>lib.save(v.id,v.raw),/其他程序/);assert.match(fs.readFileSync(file,'utf8'),/external/);assert.throws(()=>lib.create({sourceId:'original:rooms_sewer.xml',name:'下水道🐎新房间'}),/同名/);});
test('fixed scenes remain editable copies but cannot be published as random pools',()=>{const {lib}=setup();lib.scan();const v=lib.create({sourceId:'original:rooms_begin.xml',name:'我的地下通道'});assert.throws(()=>lib.publish(v.libraryId),/固定剧情/);assert.equal(v.raw,lib.get('original:rooms_begin.xml').raw);});
