'use strict';
const api=parent.workshop,M=MapDocument,K=MapCatalog,$=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let raw='',savedRaw='',doc,id,filename,index=0,selection=-1,revision=0,undo=[],redo=[],recoverTimer,previewImage,previewRevision=-1,previewIndex=-1,previewOptions=null,previewRequest,showNative=false,viewRequest=0,drag=null,space=false;
const room=()=>doc?.rooms[index],objects=()=>room()?.children.filter(n=>['obj','back'].includes(n.name))||[],dirty=()=>!!id&&raw!==savedRaw;
const notice=text=>$('notice').textContent=text;
function state(){parent.RMHost.state('map',{dirty:dirty(),revision});$('filename').textContent=filename||'我的地图';$('saved').textContent=id?(dirty()?'未保存':'已保存'):'尚未打开';$('undo').disabled=!undo.length;$('redo').disabled=!redo.length;$('empty').hidden=!!id;clearTimeout(recoverTimer);if(id)recoverTimer=setTimeout(()=>recover().catch(e=>notice('自动留存失败：'+e.message)),450);if(previewRevision!==revision||previewIndex!==index)$('png').disabled=true;}
function recover(){endDrag();return id?api.mapRecover({id,raw,revision,dirty:dirty(),roomIndex:index}):Promise.resolve(true);}
async function save(as=false){if(!id)return true;endDrag();const documentId=id,snapshot=raw,r=revision;const result=await api.mapSave({id,raw:snapshot,revision:r,as});if(!result||documentId!==id)return false;savedRaw=snapshot;filename=result.filename;state();await recover();notice('整份地图已保存，包含 '+doc.rooms.length+' 个房间。');return !dirty();}
parent.RMHost.register('map',{saveDraft:()=>save(),recover,activate:()=>draw()});
function options(){return {region:$('region').value,mirror:$('mirror').checked,objects:$('nativeObjects').checked,entities:$('entities').checked,examples:$('examples').checked,difficulty:Number($('difficulty').value)};}
function invalidatePreview(){viewRequest++;showNative=false;previewRequest=null;$('png').disabled=true;}
function trimHistory(){while(undo.length>80||undo.length>1&&undo.reduce((sum,x)=>sum+x.raw.length,0)>20000000)undo.shift();}
function changed(next,label){if(next===raw)return;M.parse(next);undo.push({raw,index,selection});trimHistory();redo=[];raw=next;revision++;invalidatePreview();refresh();notice(label||'已修改，可撤销。');}
function refresh(){doc=M.parse(raw);index=Math.min(index,doc.rooms.length-1);selection=Math.min(selection,objects().length-1);state();listRooms();props();draw();}
async function install(value){if(!value)return;id=value.id;filename=value.filename;raw=value.raw;savedRaw=value.dirty?'':raw;revision++;index=Math.max(0,Number(value.roomIndex)||0);selection=-1;undo=[];redo=[];previewImage=null;invalidatePreview();refresh();notice(value.recovered?'已恢复上次地图工作草稿。':'已打开 '+doc.rooms.length+' 个房间。');}
async function leave(){if(!dirty())return true;return parent.loot.confirm({message:'打开另一份地图前，保留当前工作草稿？',detail:'当前地图会先自动留存。建议先点“保存地图”留下一份正式文件。'}).then(async yes=>{if(yes)await recover();return yes;});}
function listRooms(){const q=$('roomSearch').value.toLowerCase();$('roomList').innerHTML=doc.rooms.map((r,i)=>({r,i})).filter(({r})=>(r.attrs.name||'').toLowerCase().includes(q)).map(({r,i})=>'<button data-room="'+i+'" class="'+(i===index?'active':'')+'">'+esc(r.attrs.name||'未命名')+'<small>位置 '+esc(r.attrs.x??'自动')+' / '+esc(r.attrs.y??'自动')+'</small></button>').join('');}
function nameFor(n){return K.objects.find(o=>o.id===n.attrs.id&&o.kind===n.name)?.label||n.attrs.id||'未知物体';}
const names={name:'房间名称',x:'横向位置（格）',y:'纵向位置（格）',z:'楼层',id:'型号编号',code:'脚本识别号',turn:'朝向（1 / -1）',lev:'等级',h:'高度',w:'宽度',tr:'转向',ai:'行为',prob:'出现概率',locked:'锁定',dif:'难度',biom:'环境类型',rnd:'随机房间'};
function field(key,value,target){return '<label>'+esc(names[key]||key)+'<input data-property="'+esc(key)+'" data-target="'+target+'" value="'+esc(value)+'"></label>';}
function props(){if(!doc)return;const r=room(),list=objects(),selected=list[selection];$('roomProps').innerHTML=['name','x','y','z'].map(k=>field(k,r.attrs[k]??'', 'room')).join('');$('roomXML').value=M.nodeXML(doc,r);$('landXML').value=doc.land?M.nodeXML(doc,doc.land):'<land/>';
 $('properties').innerHTML=selected?'<strong>'+esc(nameFor(selected))+'</strong><small> '+esc(selected.name+' / '+selected.attrs.id)+'</small>'+['x','y','turn'].map(k=>field(k,selected.attrs[k]??'', 'object')).join('')+'<button id="deleteObject">移除物体</button><details><summary>全部属性与脚本</summary><p>未填写的属性按原游戏默认值处理。</p>'+Object.entries(selected.attrs).filter(([k])=>!['x','y','turn'].includes(k)).map(([k,v])=>field(k,v,'object')).join('')+'<textarea id="objectXML" rows="9" spellcheck="false">'+esc(M.nodeXML(doc,selected))+'</textarea><button id="applyObjectXML">保存这段物体内容</button></details>':'<p>选择一个物体，查看位置和属性。拖动物体可移动，擦除可撤销。</p>';
 $('objectList').innerHTML=list.map((o,i)=>'<button data-object="'+i+'" class="'+(i===selection?'active':'')+'">'+esc(nameFor(o))+'<small>'+esc(o.attrs.id)+' · '+esc(o.attrs.x)+', '+esc(o.attrs.y)+'</small></button>').join('');
}
function palette(){const layer=$('layer').value,q=$('paletteSearch').value.toLowerCase();let entries=['obj','back'].includes(layer)?K.objects.filter(o=>o.kind===layer&&o.placeable!==false):K.materials.filter(m=>m.layer===Number(layer));entries=entries.filter(e=>(e.label+' '+e.id).toLowerCase().includes(q));$('palette').innerHTML=entries.map(e=>'<option value="'+esc(e.id)+'">'+esc(e.label)+' · '+esc(e.id||'空')+'</option>').join('');}
function visible(o){return o.name==='back'?$('backgrounds').checked:$('objects').checked;}
function draw(){ctx.fillStyle='#243330';ctx.fillRect(0,0,1920,1000);if(!doc)return;
 if(showNative&&previewImage){ctx.drawImage(previewImage,0,0);if($('labels').checked||$('ids').checked)drawLabels(objects(),previewOptions?.mirror);return;}
 const grid=M.cells(room());for(let y=0;y<25;y++)for(let x=0;x<48;x++){const code=grid[y][x];if($('back').checked&&code.slice(1)){ctx.fillStyle='#465950';ctx.fillRect(x*40,y*40,40,40);}if($('front').checked&&code[0]!=='_'){const material=K.materials.find(m=>m.id===code[0]&&m.layer===1);ctx.fillStyle=material?.color||'#91a58e';let cut=code.includes(',')?10:code.includes(';')?20:code.includes(':')?30:0;ctx.fillRect(x*40,y*40+cut,40,40-cut);ctx.fillStyle='#c8d6b477';ctx.fillRect(x*40,y*40+cut,40,2);}}
 ctx.strokeStyle='#b5c7b31b';ctx.lineWidth=1;for(let x=0;x<=48;x++){ctx.beginPath();ctx.moveTo(x*40,0);ctx.lineTo(x*40,1000);ctx.stroke();}for(let y=0;y<=25;y++){ctx.beginPath();ctx.moveTo(0,y*40);ctx.lineTo(1920,y*40);ctx.stroke();}
 const list=objects();list.forEach((o,i)=>{if(!visible(o))return;const x=Number(o.attrs.x)*40,y=Number(o.attrs.y)*40;ctx.fillStyle=o.name==='back'?'#8da9c05c':'#dec18466';ctx.fillRect(x+3,y+3,34,34);ctx.strokeStyle=i===selection?'#ffef99':o.name==='back'?'#8db8d2':'#dabf85';ctx.lineWidth=i===selection?4:2;ctx.strokeRect(x+3,y+3,34,34);});
 if($('labels').checked||$('ids').checked)drawLabels(list);
}
function drawLabels(list,mirror=false){
 const font=Math.max(12,14/Number($('zoom').value));ctx.font=font+'px "Microsoft YaHei UI", "Microsoft YaHei", sans-serif';
 const items=list.map((o,i)=>({o,i})).filter(({o})=>visible(o)).map(({o,i})=>({index:i,priority:i===selection?0:1,x:(mirror?48-Number(o.attrs.x)-Math.max(1,Number(K.objects.find(d=>d.id===o.attrs.id&&d.kind===o.name)?.size)||1):Number(o.attrs.x))*40+20,y:Number(o.attrs.y)*40+20,label:($('labels').checked?nameFor(o):'')+($('ids').checked?' ['+o.attrs.id+']':'')})).filter(o=>Number.isFinite(o.x)&&Number.isFinite(o.y));
 const result=MapLabels.layout(items,text=>ctx.measureText(text).width,1920,1000,font);
 // Sample the unlabelled image before drawing any label or leader line.
 for(const item of result.placed){const b=item.box;item.colors=MapLabels.colors([.2,.5,.8].map(t=>ctx.getImageData(Math.min(1919,Math.max(0,Math.round(b.x+b.w*t))),Math.min(999,Math.max(0,Math.round(b.y+b.h/2))),1,1).data));}
 for(const item of result.placed){const b=item.box;ctx.strokeStyle=item.colors.outline;ctx.fillStyle=item.colors.text;ctx.lineWidth=3;ctx.lineJoin='round';
  if(Math.hypot(b.x-item.x,b.y-item.y)>32){ctx.beginPath();ctx.moveTo(item.x,item.y);ctx.lineTo(b.x+3,b.y+b.h/2);ctx.stroke();ctx.save();ctx.strokeStyle=item.colors.text;ctx.lineWidth=1;ctx.stroke();ctx.restore();}
  ctx.strokeText(item.label,b.x+5,b.y+font+2);ctx.fillText(item.label,b.x+5,b.y+font+2);
 }
 canvas.dataset.hiddenLabels=String(result.hidden.length);
 if(result.hidden.length){ctx.fillStyle='#ffe6a2';ctx.strokeStyle='#15241e';ctx.lineWidth=3;const text=result.hidden.length+' 个密集标签请在右侧物体列表查看';ctx.strokeText(text,12,980);ctx.fillText(text,12,980);}
}
function at(event){const rect=canvas.getBoundingClientRect();return [Math.floor((event.clientX-rect.left)*48/rect.width),Math.floor((event.clientY-rect.top)*25/rect.height)];}
function hit(x,y){const list=objects();for(let i=list.length-1;i>=0;i--){const o=list[i],def=K.objects.find(v=>v.id===o.attrs.id&&v.kind===o.name),size=Number(def?.size)||1;if(visible(o)&&x>=Number(o.attrs.x)&&x<Number(o.attrs.x)+size&&y===Number(o.attrs.y))return i;}return -1;}
function action(x,y){const tool=$('tool').value,layer=$('layer').value;if(x<0||x>=48||y<0||y>=25)return;
 if(tool==='select'){selection=hit(x,y);props();draw();return;}
 if(tool==='paint'||tool==='erase'&&!['obj','back'].includes(layer)){if(['obj','back'].includes(layer))return notice('绘制地形时，请选择地形或墙面层。');const key=x+','+y;if(drag.points.has(key))return;drag.points.add(key);raw=M.paint(raw,index,[[x,y]],tool==='erase'?'':$('palette').value,Number(layer),K.materials,Number(layer)===1?(tool==='erase'?0:Number($('shape').value)):null);doc=M.parse(raw);draw();return;}
 if(tool==='erase'){const n=objects()[hit(x,y)];if(n){raw=M.patch(raw,[{start:n.start,end:n.end,value:''}]);doc=M.parse(raw);draw();}return;}
 if(tool==='place'){if(!['obj','back'].includes(layer))return notice('放置物体时，请选择“物体”或“背景装饰物”层。');if(drag.placed||!$('palette').value)return;drag.placed=true;const xml='<'+layer+' id="'+M.escape($('palette').value)+'" x="'+x+'" y="'+y+'"'+(layer==='obj'?' code="'+crypto.randomUUID().replaceAll('-','').slice(0,16)+'"':'')+'/>';raw=M.insert(raw,room(),xml);doc=M.parse(raw);selection=objects().length-1;draw();}
}
canvas.addEventListener('pointerdown',e=>{if(!id)return;const viewport=$('viewport');if(space||e.button===1){e.preventDefault();drag={pan:true,x:e.clientX,y:e.clientY,left:viewport.scrollLeft,top:viewport.scrollTop};canvas.setPointerCapture(e.pointerId);return;}if(e.button!==0)return;if(showNative){notice('当前是游戏预览。点击“编辑画布”后继续修改。');return;}drag={before:raw,points:new Set(),start:at(e)};canvas.setPointerCapture(e.pointerId);action(...drag.start);drag.selected=selection;});
canvas.addEventListener('pointermove',e=>{if(!drag)return;if(drag.pan){$('viewport').scrollLeft=drag.left-e.clientX+drag.x;$('viewport').scrollTop=drag.top-e.clientY+drag.y;return;}const pos=at(e);if($('tool').value==='select'){drag.end=pos;return;}action(...pos);});
function endDrag(){if(!drag)return;if(drag.pan){drag=null;return;}if($('tool').value==='select'&&drag.selected>=0&&drag.end&&drag.end.some((v,i)=>v!==drag.start[i])){const node=objects()[drag.selected];const x=Number(node.attrs.x)+drag.end[0]-drag.start[0],y=Number(node.attrs.y)+drag.end[1]-drag.start[1];if(x>=0&&x<48&&y>=0&&y<25){let n=objects()[drag.selected];raw=M.attribute(raw,n,'x',x);doc=M.parse(raw);n=objects()[drag.selected];raw=M.attribute(raw,n,'y',y);}}
 const next=raw,before=drag.before;drag=null;if(next!==before){raw=before;changed(next);}else props();}
canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);
canvas.addEventListener('contextmenu',e=>e.preventDefault());
function promptValue(title,label,value){return new Promise(resolve=>{$('dialogTitle').textContent=title;$('dialogLabel').textContent=label;$('dialogValue').value=value;$('dialog').showModal();$('dialogValue').focus();let done=false;const finish=v=>{if(done)return;done=true;$('dialog').close();resolve(v);};$('dialogCancel').onclick=()=>finish(null);$('dialogOK').onclick=()=>finish($('dialogValue').value);$('dialog').oncancel=()=>finish(null);});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;(async()=>{
 if(b.dataset.room!==undefined){index=Number(b.dataset.room);selection=-1;invalidatePreview();refresh();return;}
 if(b.dataset.object!==undefined){selection=Number(b.dataset.object);showNative=false;props();draw();return;}
 if(b.id==='new'){if(await leave())await install(await api.mapNew({fixed:$('newKind').value==='fixed'}));}
 if(b.id==='open'){if(await leave())await install(await api.mapOpen());}
 if(b.id==='save'||b.id==='saveAs')await save(b.id==='saveAs');
 if(b.id==='undo'||b.id==='redo'){const from=b.id==='undo'?undo:redo,to=b.id==='undo'?redo:undo;const previous=from.pop();if(previous){to.push({raw,index,selection});({raw,index,selection}=previous);revision++;invalidatePreview();refresh();}}
 if(b.id==='editView'){showNative=false;draw();}
 if(!id)return;
 if(['addRoom','copyRoom'].includes(b.id)){const name=await promptValue(b.id==='addRoom'?'添加房间':'复制房间','给房间起一个不重复的名称',room().attrs.name+'-新');if(!name)return;if(doc.rooms.some(r=>r.attrs.name===name))throw Error('已有同名房间，请换一个名称');let xml=b.id==='addRoom'?M.blankRoom(name,doc.random?{}:{x:Math.max(...doc.rooms.map(r=>Number(r.attrs.x)||0))+1,y:0,z:0}):M.nodeXML(doc,room());if(b.id==='copyRoom')xml=M.attribute(xml,MapXML.scanXml(xml),'name',name);changed(M.insert(raw,doc.root,xml));index=doc.rooms.length-1;refresh();}
 if(b.id==='removeRoom'){if(doc.rooms.length===1)throw Error('请至少保留一个房间');if(await parent.loot.confirm({message:'删除当前房间？',detail:room().attrs.name+'。可以撤销。'}))changed(M.patch(raw,[{start:room().start,end:room().end,value:''}]));}
 if(b.id==='deleteObject'){const n=objects()[selection];if(n)changed(M.patch(raw,[{start:n.start,end:n.end,value:''}]));}
 if(['applyRoomXML','applyObjectXML','applyLandXML'].includes(b.id)){const target=b.id==='applyRoomXML'?room():b.id==='applyLandXML'?doc.land:objects()[selection],value=$(b.id==='applyRoomXML'?'roomXML':b.id==='applyLandXML'?'landXML':'objectXML').value,node=MapXML.scanXml(value);if(target&&node.name!==target.name)throw Error('不能改变这段内容的种类');if(!target&&node.name!=='land')throw Error('地区设置需要 land 标记');changed(target?M.patch(raw,[{start:target.start,end:target.end,value}]):M.insert(raw,doc.root,value));}
 if(b.id==='preview'){const token=++viewRequest,r=revision,selectedIndex=index,documentId=id,source=raw,settings=options();b.disabled=true;notice('正在读取原生素材并绘制，首次需要稍等…');try{const ready=await api.rendererReady();if($('region').options.length===1)$('region').insertAdjacentHTML('beforeend',ready.regions.map(v=>'<option value="'+esc(v.id)+'">'+esc(v.label)+'</option>').join(''));const result=await api.mapPreview({id:documentId,raw:source,index:selectedIndex,revision:r,options:settings});if(token!==viewRequest||r!==revision||selectedIndex!==index)return;const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=result.image;});if(token!==viewRequest||r!==revision)return;previewImage=image;previewRevision=r;previewIndex=selectedIndex;previewOptions=settings;previewRequest=result.requestId;showNative=true;draw();$('png').disabled=false;$('previewNote').textContent='原生静态预览 · '+result.report.regionName+' · 固定角色 '+result.report.entities+' · 随机点示例 '+result.report.examples+(result.report.warnings.length?' · 提醒：'+result.report.warnings.join('；'):'');notice('预览已生成。点击“编辑画布”返回编辑；镜像只影响预览。');}finally{b.disabled=false;}}
 if(b.id==='png'&&previewRequest){const saved=await api.mapPNG(previewRequest);if(saved)notice('PNG 已保存：'+saved);}
})().catch(e=>notice(e.message||String(e)));});
document.addEventListener('change',e=>{const t=e.target;try{if(t.dataset.property){if(!id)return;const n=t.dataset.target==='room'?room():objects()[selection],key=t.dataset.property;if(t.dataset.target==='room'&&key==='name'&&(!t.value.trim()||doc.rooms.some((r,i)=>i!==index&&r.attrs.name===t.value)))throw Error('房间名称不能为空或重复');if(['x','y','z','turn'].includes(key)&&t.value!==''&&!/^-?\d+$/.test(t.value))throw Error('位置和朝向请填写整数');changed(M.attribute(raw,n,key,t.value===''?null:t.value));}else if(t.id==='layer'){palette();if(['obj','back'].includes(t.value)&&$('tool').value==='paint')$('tool').value='place';}else if(t.id==='zoom'){canvas.style.width=1920*Number(t.value)+'px';canvas.style.height=1000*Number(t.value)+'px';draw();}else if(['front','back','objects','backgrounds','labels','ids'].includes(t.id)){if(['front','back','objects','backgrounds'].includes(t.id))showNative=false;draw();}else if(['region','mirror','nativeObjects','entities','examples','difficulty'].includes(t.id)){invalidatePreview();draw();notice('预览设置已改变，点击“查看游戏画面”重新生成。');}}catch(e){notice(e.message);props();}});
$('roomSearch').oninput=()=>doc&&listRooms();$('paletteSearch').oninput=palette;
document.addEventListener('keydown',e=>{if(e.isComposing)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(e=>notice(e.message));return;}if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();space=true;}if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();$('redo').click();}if(e.key==='Delete')$('deleteObject')?.click();});
document.addEventListener('keyup',e=>{if(e.code==='Space')space=false;});window.addEventListener('blur',()=>{space=false;endDrag();});
palette();state();api.mapBoot().then(install).catch(e=>notice('上次地图无法恢复，原文件仍保留：'+e.message));
