"""Generate map-owned Node/browser metadata from the frozen editor definitions and Chinese text."""
from pathlib import Path
import argparse
import hashlib
import json
import xml.etree.ElementTree as ET

component = Path(__file__).resolve().parents[1]
project = component.parent
parser = argparse.ArgumentParser()
parser.add_argument('--game-root', type=Path, default=project.parent.parent)
args = parser.parse_args()
legacy = component / 'legacy/scripts/fe/AllData.as'
source = legacy.read_text(encoding='utf-8-sig')
definitions = ET.fromstring(source[source.index('<all>'):source.index('</all>') + 6])
localization = component / 'localization'
localization.mkdir(exist_ok=True)
for name, origin in [('editor-zh.xml', args.game_root / 'Editor/Resources/text_zh.xml'),
                     ('game-zh.xml', args.game_root / 'text_zh.xml')]:
    target = localization / name
    if not target.exists():
        target.write_bytes(origin.read_bytes())
editor = ET.parse(localization / 'editor-zh.xml').getroot()
game = ET.parse(localization / 'game-zh.xml').getroot()
lookup = {e.get('id'): e.findtext('n') for e in editor if e.findtext('n')}
official = {(e.tag, e.get('id')): e.findtext('n') for e in game if e.findtext('n')}
colors = ['#789d80', '#959791', '#6d7478', '#727472', '#838580', '#a6a287', '#82715b', '#806b52', '#927c6c', '#8c9390', '#7b817d', '#547963', '#b29d69', '#798786', '#758286', '#967495', '#637d89', '#557080', '#658cab', '#668994']
materials = []
for e in definitions.findall('mat'):
    if int(e.get('ed', '0')) <= 0:
        continue
    materials.append(dict(e.attrib, layer=int(e.get('ed')), label=lookup.get(e.get('n')) or e.get('n') or e.get('id'), color=colors[len(materials) % len(colors)]))
materials.append({'id': '*', 'ed': '5', 'layer': 5, 'label': lookup.get('Вода', '水'), 'color': '#529cac'})
# These four hidden definitions were not present in the legacy editor palette.
# Descriptive labels stay separate from game identifiers; official names take priority.
hidden_labels = {'exit_light': '出口灯', 'h109': '背景标记（h109）', 'qgraff': '涂鸦（qgraff）', 'pink': '粉雾'}
objects = []
for kind in ['obj', 'back']:
    for e in definitions.findall(kind):
        if kind == 'obj' and int(e.get('ed', '0')) <= 0:
            continue
        key = e.get('id')
        if not key:
            continue
        label = official.get((kind, key)) or official.get(('unit', key)) or lookup.get(key) or lookup.get(e.get('n')) or hidden_labels.get(key) or key
        objects.append(dict(e.attrib, kind=kind, label=label, placeable=e.get('nope') != '1'))
result = {'materials': materials, 'objects': objects, 'sources': {
    str(p.relative_to(project)).replace('\\', '/'): hashlib.sha256(p.read_bytes()).hexdigest()
    for p in [legacy, localization / 'editor-zh.xml', localization / 'game-zh.xml']}}
encoded = json.dumps(result, ensure_ascii=False, indent=2) + '\n'
(project / 'desktop/map/catalog.json').write_text(encoded, encoding='utf-8')
(project / 'desktop/ui/map/catalog.js').write_text('/* Generated by map-editor/tools/generate_catalog.py */\nglobalThis.MapCatalog = ' + encoded.strip() + ';\n', encoding='utf-8')
untranslated = [e['id'] for e in materials + objects if not any('\u4e00' <= c <= '\u9fff' for c in e['label'])]
print(json.dumps({'materials': len(materials), 'objects': len(objects), 'untranslated': untranslated}, ensure_ascii=False))
if untranslated:
    raise SystemExit('Untranslated catalog entries require review')
